type: SEC_NMT

preprocessing: ${from_file:preprocessing/mixed_noise.yaml}
input_tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
output_tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}

data_scheme: "word_graph"
add_word_features: ${oc.env:GNN_LIB_ADD_WORD_FEATURES,true}
token_fully_connected: ${oc.env:GNN_LIB_TOKEN_FULLY_CONNECTED,false}
word_fully_connected: ${oc.env:GNN_LIB_TOKEN_FULLY_CONNECTED,true}
