type: SED_WORDS

noise: ${from_file:preprocessing/mixed.yaml}
tokenizer: ${from_file:tokenizer/bpe_default.yaml}

encoding_scheme: "whitespace_words"
add_word_features: ${oc.env:GNN_LIB_ADD_WORD_FEATURES,true}
dictionary_file: ${oc.env:GNN_LIB_DICTIONARY,null} #${oc.env:GNN_LIB_DATA_DIR}/dictionaries/merged_train_100k.txt}

# special args for encoding scheme whitespace_words
add_dependency_info: ${oc.env:GNN_LIB_ADD_DEPENDENCY_INFO,false}
word_fully_connected: ${oc.env:GNN_LIB_WORD_FULLY_CONNECTED,false}
token_fully_connected: ${oc.env:GNN_LIB_TOKEN_FULLY_CONNECTED,true}
index: ${oc.env:GNN_LIB_SPELL_CHECK_INDEX,null}
