type: SED_WORDS

noise: ${from_file:preprocessing/mixed.yaml}
tokenizer: ${from_file:tokenizer/bpe_default.yaml}

encoding_scheme: "tokens"
add_word_features: ${oc.env:GNN_LIB_ADD_WORD_FEATURES,false}
dictionary_file: ${oc.env:GNN_LIB_DICTIONARY,${oc.env:GNN_LIB_DATA_DIR}/dictionaries/merged_train_100k.txt}
