type: SED_SEQUENCE

preprocessing: ${from_file:preprocessing/mixed_noise_sed_sequence.yaml}
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}

data_scheme: "tensor"

add_word_features: ${oc.env:GNN_LIB_ADD_WORD_FEATURES,true}
dictionary_file: ${oc.env:GNN_LIB_DICTIONARY,${oc.env:GNN_LIB_DATA_DIR}/dictionaries/merged_train_100k.txt}
