type: SED_WORDS

preprocessing: ${from_file:preprocessing/mixed_noise.yaml}
tokenizer: ${from_file:tokenizer/bpe_default.yaml}

data_scheme: "word_graph"

add_word_features: ${oc.env:GNN_LIB_ADD_WORD_FEATURES,true}
dictionary_file: ${oc.env:GNN_LIB_DICTIONARY,${oc.env:GNN_LIB_DATA_DIR}/dictionaries/merged_train_100k.txt}

# special args for data scheme word_graph
add_dependency_info: ${oc.env:GNN_LIB_ADD_DEPENDENCY_INFO,false}
word_fully_connected: ${oc.env:GNN_LIB_WORD_FULLY_CONNECTED,true}
token_fully_connected: ${oc.env:GNN_LIB_TOKEN_FULLY_CONNECTED,false}
index: ${oc.env:GNN_LIB_SPELL_CHECK_INDEX,null}
