type: TOKENIZATION_REPAIR_PLUS

preprocessing: ${from_file:preprocessing/tokenization_repair_plus.yaml}

data_scheme: "tensor"
tokenization_level: "char"

output_type: "tokenization_repair_plus_sed"
fix_tokenization_repair: ${oc.env:GNN_LIB_FIX_TOKENIZATION_REPAIR,false}

add_word_features: ${oc.env:GNN_LIB_ADD_WORD_FEATURES,true}
dictionary_file: ${oc.env:GNN_LIB_DICTIONARY,${oc.env:GNN_LIB_DATA_DIR}/dictionaries/merged_train_100k.txt}
