type: GENERAL_GNN

num_layers: ${oc.env:NSC_NUM_LAYERS,6}
dropout: 0.1
norm: layer
message_scheme: ${oc.env:NSC_MESSAGE_SCHEME,attention}
message_gating: ${oc.env:NSC_MESSAGE_GATING,false}
node_update: ${oc.env:NSC_NODE_UPDATE,residual}
share_parameters: ${oc.env:NSC_SHARE_PARAMETERS,false}
