type: CHAINED
cfgs:
  - ${from_file:preprocessing/mixed_noise.yaml}
  - type: WHITESPACE_NOISE
    no_whitespace_p: 0.1
    full_whitespace_p: 0.1
    insert_whitespace_p: 0.1
    delete_whitespace_p: 0.5
overwrites:
  - false
  - false
