type: SWITCH
cfgs:
  - type: MIXED_NOISE
    edit_token_p: 0.05
    min_edit_tokens: 1
    artificial_num_edits_p: 0.8
    word_misspellings_file: ${oc.env:NSC_DATA_DIR}/misspellings/train_misspellings.json
    artificial_p: 0.2
    re_weight_edit_token_p: true
  - type: NONE
probabilities: [0.5, 0.5]
