type: CHAINED
cfgs:
  - ${from_file:preprocessing/mixed.yaml}
  - type: WHITESPACE_NOISE
    no_whitespace_p: 0.2
    insert_whitespace_p: 0.1
    delete_whitespace_p: 0.2
overrides:
  - true
  - false
