type: MODEL_FOR_TOKEN_CLASSIFICATION

embedding: ${from_file:embedding/token_embedding.yaml}

hidden_dim: ${oc.env:GNN_LIB_HIDDEN_DIM,512}
dropout: 0.1
num_layers: ${oc.env:GNN_LIB_NUM_ENCODER_LAYERS,6}

num_classes: 2

tokenizer: ${from_file:tokenizer/bpe_default.yaml}
