type: MODEL_FOR_TOKENIZATION_REPAIR_PLUS

embedding: ${from_file:embedding/token_embedding.yaml}
max_length: 512

hidden_dim: ${oc.env:GNN_LIB_HIDDEN_DIM,512}
dropout: 0.1

input_type: "char"
output_type: "tokenization_repair_plus_sed_plus_sec"

num_input_layers: ${oc.env:GNN_LIB_NUM_INPUT_LAYERS,6}
num_word_layers: ${oc.env:GNN_LIB_NUM_WORD_LAYERS,6}

start_from_tokenization_repair_checkpoint: ${oc.env:GNN_LIB_START_FROM_TOKENIZATION_REPAIR_CHECKPOINT,null}
fix_tokenization_repair: ${oc.env:GNN_LIB_FIX_TOKENIZATION_REPAIR,false}

num_sec_layers: ${oc.env:GNN_LIB_NUM_SEC_LAYERS,6}
sec_tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
sec_max_output_length: 1024
