type: MODEL_FOR_MULTI_NODE_CLASSIFICATION

embedding: ${from_file:embedding/node_embedding.yaml}
gnn: ${from_file:gnn/transformer_encoder_gnn.yaml}

node_hidden_dim: ${oc.env:GNN_LIB_HIDDEN_DIM,512}
edge_hidden_dim: ${oc.env:GNN_LIB_EDGE_HIDDEN_DIM,256}
hidden_feature: "h"

num_classes:
  token: 3

tokenizers:
  token:
    type: CHAR
