type: MODEL_FOR_GRAPH_CLASSIFICATION

embedding: ${from_file:embedding/node_embedding.yaml}
gnn: ${from_file:gnn/general_gnn.yaml}

node_hidden_dim: ${oc.env:GNN_LIB_HIDDEN_DIM,512}
edge_hidden_dim: ${oc.env:GNN_LIB_EDGE_HIDDEN_DIM,256}
hidden_feature: "h"

num_classes: 2
node_type: "sequence"
pooling_type: "mean"

tokenizers:
  token: ${from_file:tokenizer/bpe_default.yaml}
