type: MODEL_FOR_TOKENIZATION_REPAIR_PLUS

embedding: ${from_file:embedding/token_embedding.yaml}

hidden_dim: ${oc.env:GNN_LIB_HIDDEN_DIM,512}
dropout: 0.1

input_type: "char"
output_type: "tokenization_repair_plus_sed"

num_input_layers: ${oc.env:GNN_LIB_NUM_INPUT_LAYERS,12}
num_word_layers: ${oc.env:GNN_LIB_NUM_WORD_LAYERS,6}

num_sec_layers: ${oc.env:GNN_LIB_NUM_WORD_LAYERS,6}
