type: MODEL_FOR_SEQ2SEQ

embedding: ${from_file:embedding/token_embedding.yaml}
max_length: ${oc.env:NSC_MAX_INPUT_LENGTH,512}
max_output_length: ${oc.env:NSC_MAX_OUTPUT_LENGTH,1024}

hidden_dim: ${oc.env:NSC_HIDDEN_DIM,512}
dropout: 0.1
num_encoder_layers: ${oc.env:NSC_NUM_ENCODER_LAYERS,6}
num_decoder_layers: ${oc.env:NSC_NUM_DECODER_LAYERS,6}

input_tokenizer:
  type: CHAR
output_tokenizer:
  type: CHAR
