type: MODEL_FOR_MULTI_NODE2SEQ

embedding: ${from_file:embedding/node_embedding.yaml}
gnn: ${from_file:gnn/general_gnn.yaml}

node_hidden_dim: ${oc.env:NSC_HIDDEN_DIM,512}
edge_hidden_dim: ${oc.env:NSC_EDGE_HIDDEN_DIM,256}
hidden_feature: "h"

input_tokenizers:
  token: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
output_tokenizers:
  word: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
max_length: 512
max_output_length: 1024

decoder_node_types: ["word"]
context_node_types:
  word: ["token"]
align_positions_with:
  word: "token"

decoder_dropout: 0.1
num_decoder_layers: ${oc.env:NSC_NUM_DECODER_LAYERS,6}
