type: MODEL_FOR_TOKEN_CLASSIFICATION

embedding: ${from_file:embedding/token_embedding.yaml}

hidden_dim: ${oc.env:NSC_HIDDEN_DIM,512}
dropout: 0.1
num_layers: ${oc.env:NSC_NUM_ENCODER_LAYERS,6}

num_classes: 3

tokenizer:
  type: CHAR
