type: SED_SEQUENCE

preprocessing: ${from_file:preprocessing/mixed_noise_sed_sequence.yaml}
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}

data_scheme: "word_graph"

add_word_features: ${oc.env:NSC_ADD_WORD_FEATURES,true}
dictionary_file: ${oc.env:NSC_DICTIONARY,${oc.env:NSC_DATA_DIR}/dictionaries/merged_train_100k.txt}

# special args for data scheme word_graph
add_dependency_info: ${oc.env:NSC_ADD_DEPENDENCY_INFO,false}
word_fully_connected: ${oc.env:NSC_WORD_FULLY_CONNECTED,true}
token_fully_connected: ${oc.env:NSC_TOKEN_FULLY_CONNECTED,false}
index: ${oc.env:NSC_SPELL_CHECK_INDEX,null}
