type: SED_SEQUENCE

tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}

data_scheme: "tensor"

add_word_features: ${oc.env:NSC_ADD_WORD_FEATURES,true}
dictionary_file: ${oc.env:NSC_DICTIONARY,${oc.env:NSC_DATA_DIR}/dictionaries/merged_train_100k.txt}
