version: "3"

services:
  languagetool:
    image: erikvl87/languagetool
    ports:
      - "8010"
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    volumes:
      - ./ngram_data:/ngrams
    networks:
      - default
  languagetool_load_balance:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8010:8010"
    depends_on:
      - languagetool

networks:
  default:

