variant: ${from_file:variant/sed_sequence.yaml}
model: ${from_file:model/model_for_sed_sequence.yaml}
optimizer: ${from_file:optimizer/adamw.yaml}
lr_scheduler: ${from_file:lr_scheduler/linear_with_0.05_warmup.yaml}
start_from_checkpoint: ${oc.env:NSC_START_FROM_CHECKPOINT}

experiment_dir: ${oc.env:NSC_EXPERIMENT_DIR}
data_dir: ${oc.env:NSC_DATA_DIR}
datasets:
  - ${oc.env:NSC_DATA_DIR}/processed/neuspell_sed_sequence
dataset_limits:
  - ${oc.env:NSC_DATA_LIMIT,100000000}
val_splits:
  - 5000

experiment_name: ${oc.env:NSC_EXPERIMENT_NAME}
epochs: ${oc.env:NSC_EPOCHS,5}
batch_max_length: ${oc.env:NSC_BATCH_MAX_LENGTH,8192}
bucket_span: ${oc.env:NSC_BUCKET_SPAN,4}
log_per_epoch: ${oc.env:NSC_LOG_PER_EPOCH,100}
eval_per_epoch: ${oc.env:NSC_EVAL_PER_EPOCH,10}
seed: 22
mixed_precision: ${oc.env:NSC_MIXED_PRECISION,true}
