data:
  - ${oc.env:GNN_LIB_DATA_DIR}/cleaned/wikidump_paragraphs/train_files.txt

output_dir: ${oc.env:GNN_LIB_DATA_DIR}/processed/wikidump_paragraphs_sed_sequence
seed: 22
limit: ${oc.env:GNN_LIB_LIMIT,100000000}

max_length: 512
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
preprocessing: ${from_file:preprocessing/mixed_noise_sed_sequence.yaml}
