data:
  - ${oc.env:GNN_LIB_DATA_DIR}/cleaned/arxiv/*.jsonl

output_dir: ${oc.env:GNN_LIB_DATA_DIR}/processed/arxiv_tokenization_repair_plus
seed: 22
limit: ${oc.env:GNN_LIB_LIMIT,200000000}

max_length: 512
tokenizer:
  type: CHAR
preprocessing: ${from_file:preprocessing/tokenization_repair_plus_arxiv.yaml}
respect_leading_whitespaces: true
