data:
  - ${oc.env:GNN_LIB_DATA_DIR}/cleaned/neuspell/split/*.jsonl

output_dir: ${oc.env:GNN_LIB_DATA_DIR}/processed/neuspell_no_prefix_space
seed: 22
limit: ${oc.env:GNN_LIB_LIMIT,50000000}

max_length: 512
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
preprocessing:
  type: NONE

with_dep_parser: true
