data:
  - ${oc.env:NSC_DATA_DIR}/cleaned/neuspell/*.jsonl

output_dir: ${oc.env:NSC_DATA_DIR}/processed/neuspell
seed: 22
limit: ${oc.env:NSC_LIMIT,100000000}

max_length: 512
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
preprocessing:
  type: NONE
