data:
  - ${oc.env:NSC_DATA_DIR}/cleaned/wikidump_paragraphs/train_files.txt

output_dir: ${oc.env:NSC_DATA_DIR}/processed/wikidump_paragraphs_sed_words_and_sec
seed: 22
limit: ${oc.env:NSC_LIMIT,100000000}

max_length: 512
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
preprocessing: ${from_file:preprocessing/mixed_noise.yaml}

with_dep_parser: true
