data:
  - ${oc.env:NSC_DATA_DIR}/cleaned/bookcorpus_paragraphs/train_files.txt

output_dir: ${oc.env:NSC_DATA_DIR}/processed/bookcorpus_paragraphs_sed_words_and_sec${oc.env:NSC_OUTPUT_DIR_POSTFIX,}
seed: 22
limit: ${oc.env:NSC_LIMIT,100000000}

max_length: 512
tokenizer: ${from_file:tokenizer/bpe_no_prefix_space.yaml}
preprocessing: ${from_file:preprocessing/mixed_noise.yaml}

with_dep_parser: true
